# Generated by Django 5.0.1 on 2024-02-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='image',
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.URLField(),
        ),
    ]
